backend:
  name: github
  repo: Youssef1241/tff-website
  branch: main
  base_url: https://tff-website-mu.vercel.app
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "test"
    label: "Test"
    folder: "_test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }