backend:
  name: github
  repo: Youssef1241/tff-website
  branch: main

media_folder: "images"

collections:
  - name: "courses"
    label: "Courses"
    files:
      - name: "courses-en"
        label: "Courses (English)"
        file: "_data/courses-en.json"
        fields:
          - label: "Courses"
            name: "courses"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "uuid" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }

      - name: "courses-ar"
        label: "Courses (Arabic)"
        file: "_data/courses-ar.json"
        fields:
          - label: "Courses"
            name: "courses"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "uuid" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown" }

  - name: "newsletter"
    label: "Newsletter"
    files:
      - name: "newsletter-en"
        label: "Newsletter (English)"
        file: "_data/newsletter-en.json"
        fields:
          - label: "Issues"
            name: "issues"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "uuid" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown" }

      - name: "newsletter-ar"
        label: "Newsletter (Arabic)"
        file: "_data/newsletter-ar.json"
        fields:
          - label: "Issues"
            name: "issues"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "uuid" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Body", name: "body", widget: "markdown" }